id: IDBC8844B
legacy_id: P003198
ocr_import_info:
  bdrc_scan_id: W30154
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T10:33:46'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T11:21:42.114502+00:00'
last_modified: 2022-09-03 19:21:56.602088
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W30154
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW30154
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཚངས་དབྱངས་རྒྱ་མཚོའི་གསང་བའི་རྣམ་ཐར་སོགས།
  author: ལྷ་བཙུན་ངག་དབང་རྡོ་རྗེ།
statistics:
  ocr_word_mean_confidence_index: 0.6683559741023736
  ocr_word_median_confidence_index: 0.7200000286102295
quality: null
bases:
  I5944:
    source_metadata:
      id: http://purl.bdrc.io/resource/I5944
      total_pages: 482
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I5944.txt
    statistics:
      ocr_word_median_confidence_index: 0.7200000286102295
      ocr_word_mean_confidence_index: 0.6683559741023736
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
