id: IDBC8844B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T10:36:55+00:00'
last_modified: '2022-06-07T18:20:50.935757+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W30154
  title: ཚངས་དབྱངས་རྒྱ་མཚོའི་གསང་བའི་རྣམ་ཐར་སོགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    2D04:
      image_group_id: I5944
      title: ''
      total_pages: 482
      order: 1
      base_file: 2D04.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
