id: P003198
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 10:46:53.570495
source_metadata:
  id: bdr:W30154
  title: ཚངས་དབྱངས་རྒྱ་མཚོའི་གསང་བའི་རྣམ་ཐར་སོགས།
  author: ''
  volumes:
    25dc581c6812460a972801218807e3f8:
      image_group_id: I5944
      title: ''
      volume_number: 1
      total_pages: 482
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
